

export const departments = [
  { name: "Administration" },
  { name: "Audit" },
  { name: "Banking Operations" },
  { name: "Communications" },
  { name: "Corporate Services" },
  { name: "Facilities" },
  { name: "Financial Services" },
  { name: "Human Resources" },
  { name: "Information Technology" },
  { name: "IT Technician" },
];

// Employees
export const employees = [
  // Department employees
  { name: "Zoë Robins", departmentName: "Administration" },
  { name: "Madeleine Madden", departmentName: "Administration" },
  { name: "Josha Sadowski", departmentName: "Audit" },
  { name: "Kate Fleetwood", departmentName: "Audit" },
  { name: "Priyanka Bose", departmentName: "Banking Operations" },
  { name: "Hammed Animashaun", departmentName: "Banking Operations" },
  { name: "Álvaro Morte", departmentName: "Banking Operations" },
  { name: "Taylor Napier", departmentName: "Banking Operations" },
  { name: "Alan Simmonds", departmentName: "Banking Operations" },
  { name: "Gil Cardinal", departmentName: "Communications" },
  { name: "Richard J. Lewis", departmentName: "Communications" },
  { name: "Randy Bradshaw", departmentName: "Corporate Services" },
  { name: "Tracey Cook", departmentName: "Corporate Services" },
  { name: "Lubomir Mykytiuk", departmentName: "Corporate Services" },
  { name: "Dakota House", departmentName: "Facilities" },
  { name: "Lori Lea Okemah", departmentName: "Facilities" },
  { name: "Renae Morrisseau", departmentName: "Facilities" },
  { name: "Rick Belcourt", departmentName: "Facilities" },
  { name: "Selina Hanusa", departmentName: "Financial Services" },
  { name: "Buffy Gaudry", departmentName: "Financial Services" },
  { name: "Shaneen Ann Fox", departmentName: "Financial Services" },
  { name: "Allan Little", departmentName: "Financial Services" },
  { name: "Danny Rabbit", departmentName: "Financial Services" },
  { name: "Jesse Ed Azure", departmentName: "Human Resources" },
  { name: "Stacy Da Silva", departmentName: "Human Resources" },
  { name: "Vladimír Valenta", departmentName: "Human Resources" },
  { name: "Samone Sayeses-Whitney", departmentName: "Human Resources" },
  { name: "Paul Coeur", departmentName: "Human Resources" },
  { name: "Graham Greene", departmentName: "Information Technology" },
  { name: "Sandika Evergreen", departmentName: "Information Technology" },
  { name: "Jennifer Rodriguez (Software Developer)", departmentName: "Information Technology" },
  { name: "Aiyana Littlebear", departmentName: "IT Technician" },
  { name: "Inara Thunderbird", departmentName: "IT Technician" },
  { name: "Kaya Runningbrook", departmentName: "IT Technician" },
  { name: "Elara Firehawk", departmentName: "IT Technician" },
  { name: "Siona Moonflower", departmentName: "IT Technician" },
  { name: "Kaiyu Greywolf", departmentName: "IT Technician" },
  { name: "Ayawamat Nightwind", departmentName: "IT Technician" },
  { name: "Tala Braveheart", departmentName: "IT Technician" },
  { name: "Iniko Stonebear", departmentName: "IT Technician" },
  { name: "Onatah Redhawk", departmentName: "IT Technician" },

  // Role-only employees (no department)
  { name: "Jo-Anne Sinclair" },
  { name: "Jackson Smith" },
  { name: "Susan Thomas" },
  { name: "Richa Kaur" },
  { name: "Josee Benjamin" },
  { name: "Vincent Grey" },
  { name: "Rupa Kharki" },
  { name: "Xun Kuang" },
  { name: "Stien Pedersen" },
  { name: "Sandra Bear" },
  { name: "Gus Blue" },
  { name: "Sam Kong" },
  { name: "Valentine Smith" },
  { name: "Mariya Kaperski" },
  { name: "Abd al-Hamid Alami" },
  { name: "Victoria Gray" },
  { name: "Cheryl Guru" },
  { name: "Jean Ngoy" },
  { name: "Kris Gold" },
  { name: "Isaac Smith" },
  { name: "Payton Frost" },
  { name: "Samantha Nettle" },
  { name: "Yolanda Ferreira" },
  { name: "Samir Hassan" },
  { name: "Yuna Aikawa" },
  { name: "Jonathan Carberry" },
  { name: "Roland Wei" },
  { name: "Pran Singh" },
  { name: "Linda Analyst" },
  { name: "Esra Sedge" },
  { name: "Pranee Tan" },
  { name: "Karmen Spruce" },
  { name: "Haydar Katirci" },
  { name: "Jill Harkness" },
  { name: "Tim Morrison" },
  { name: "Aleksandr Milosevic" },
  { name: "Jim Wingnut" },
];

export const roles = [
  { roleName: "CEO/Chair of Board", employeeName: "Jo-Anne Sinclair" },
  { roleName: "COO/VP Operations", employeeName: "Jackson Smith" },
  { roleName: "CFO/VP Administration", employeeName: "Susan Thomas" },
  { roleName: "VP Client Services", employeeName: "Richa Kaur" },
  { roleName: "CIO", employeeName: "Josee Benjamin" },
  { roleName: "VP Sales & Marketing", employeeName: "Vincent Grey" },
  { roleName: "Director Financial and Audit Services", employeeName: "Rupa Kharki" },
  { roleName: "Director Human Resources", employeeName: "Xun Kuang" },
  { roleName: "Director Legal Services/General Counsel", employeeName: "Stien Pedersen" },
  { roleName: "Director Information Technology", employeeName: "Sandra Bear" },
  { roleName: "Director Information Security and CISSO", employeeName: "Gus Blue" },
  { roleName: "Director Accounting", employeeName: "Sam Kong" },
  { roleName: "Director Physical Security", employeeName: "Valentine Smith" },
  { roleName: "Director Facilities", employeeName: "Mariya Kaperski" },
  { roleName: "Manager, Business Continuity and Disaster Recovery", employeeName: "Abd al-Hamid Alami" },
  { roleName: "Manager, Internal Audit", employeeName: "Victoria Gray" },
  { roleName: "Chief Architect", employeeName: "Cheryl Guru" },
  { roleName: "Manager, Security Architecture", employeeName: "Jean Ngoy" },
  { roleName: "Solution Architect, Online Banking", employeeName: "Kris Gold" },
  { roleName: "Manager, Application Solutions", employeeName: "Isaac Smith" },
  { roleName: "Lead Developer, Online Banking", employeeName: "Payton Frost" },
  { roleName: "Manager, Operational Risk", employeeName: "Samantha Nettle" },
  { roleName: "Manager, Vendor Relations", employeeName: "Yolanda Ferreira" },
  { roleName: "Manager, Purchasing", employeeName: "Samir Hassan" },
  { roleName: "Manager, Communications", employeeName: "Yuna Aikawa" },
  { roleName: "Manager Customer Experience and Community Engagement", employeeName: "Jonathan Carberry" },
  { roleName: "Manager of Sales", employeeName: "Roland Wei" },
  { roleName: "Manager, Marketing", employeeName: "Pran Singh" },
  { roleName: "Business Analyst, Online Banking", employeeName: "Linda Analyst" },
  { roleName: "Manager, Contract Management", employeeName: "Esra Sedge" },
  { roleName: "Manager, Compliance Management", employeeName: "Pranee Tan" },
  { roleName: "Manager IT End User Service Desk", employeeName: "Karmen Spruce" },
  { roleName: "Manager IT End User Computing", employeeName: "Haydar Katirci" },
  { roleName: "Manager IT Telecom and Infrastructure", employeeName: "Jill Harkness" },
  { roleName: "Manager, Data Center and Hosting Services", employeeName: "Tim Morrison" },
  { roleName: "Manager of IT Risk Management", employeeName: "Aleksandr Milosevic" },
  { roleName: "Manager IT, Project Management Office", employeeName: "Jim Wingnut" },
];